terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    time = {
      source  = "hashicorp/time"
      version = "~> 0.13"
    }
  }
}

resource "aws_s3_bucket" "this" {
  bucket = var.bucket_name
}

resource "aws_s3_bucket_versioning" "this" {
  bucket = aws_s3_bucket.this.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_public_access_block" "this" {
  bucket = aws_s3_bucket.this.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

data "aws_caller_identity" "current" {}

locals {
  # Computed rather than referenced from aws_iam_role.uc_access to avoid a self-reference cycle.
  role_name     = "${var.bucket_name}-uc-access"
  self_role_arn = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${local.role_name}"
}

# Matches the shape generated by the databricks_aws_unity_catalog_assume_role_policy
# data source (see terraform-provider-databricks aws/data_aws_unity_catalog_assume_role_policy.go):
# Unity Catalog requires a self-assume statement trusting the account root, scoped down
# to this specific role via an ArnLike condition on aws:PrincipalArn.
data "aws_iam_policy_document" "assume_role" {
  statement {
    sid     = "UnityCatalogAssumeRole"
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = [var.databricks_account_iam_arn]
    }

    dynamic "condition" {
      for_each = var.uc_external_id == "" ? [] : [var.uc_external_id]
      content {
        test     = "StringEquals"
        variable = "sts:ExternalId"
        values   = [condition.value]
      }
    }
  }

  statement {
    sid     = "ExplicitSelfRoleAssumption"
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"]
    }

    condition {
      test     = "ArnLike"
      variable = "aws:PrincipalArn"
      values   = [local.self_role_arn]
    }
  }
}

resource "aws_iam_role" "uc_access" {
  name               = local.role_name
  assume_role_policy = data.aws_iam_policy_document.assume_role.json
}

data "aws_iam_policy_document" "bucket_access" {
  statement {
    effect = "Allow"
    actions = [
      "s3:GetObject",
      "s3:PutObject",
      "s3:DeleteObject",
    ]
    resources = ["${aws_s3_bucket.this.arn}/*"]
  }

  statement {
    effect    = "Allow"
    actions   = ["s3:ListBucket", "s3:GetBucketLocation"]
    resources = [aws_s3_bucket.this.arn]
  }

  # Required for the role's self-assume trust statement to actually succeed:
  # the identity-based policy must also grant the role permission to assume itself.
  statement {
    effect    = "Allow"
    actions   = ["sts:AssumeRole"]
    resources = [local.self_role_arn]
  }
}

resource "aws_iam_role_policy" "bucket_access" {
  name   = "${var.bucket_name}-bucket-access"
  role   = aws_iam_role.uc_access.id
  policy = data.aws_iam_policy_document.bucket_access.json
}

# IAM role/policy changes need a moment to propagate before Databricks validates
# access to the bucket when creating the storage credential / external location.
resource "time_sleep" "iam_propagation" {
  depends_on      = [aws_iam_role_policy.bucket_access, aws_iam_role.uc_access]
  create_duration = "20s"

  triggers = {
    assume_role_policy   = data.aws_iam_policy_document.assume_role.json
    bucket_access_policy = data.aws_iam_policy_document.bucket_access.json
  }
}
